python Golore/run_glue.py \
    --model_name_or_path roberta-base \
    --task_name cola \
    --lora_all_modules \
    --max_length 512 \
    --seed 42 \
    --lora_r 4 \
    --scale 4 \
    --per_device_train_batch_size 32 \
    --update_proj_gap 500 \
    --num_train_epochs 30 \
    --output_dir ./results/ft/roberta_base/cola/sift \
    --learning_rate 2.5e-5 \
    --rand_ratio 0.8 \
    --enable_sift
